/* eslint-disable global-require */
const images = {
  splash: require('../assests/images/welcome.png'),
  logo: require('../assests/images/logo.png'),
  google: require('../assests/images/Google.png'),
  Camera: require('../assests/images/camera.png'),
  Plug: require('../assests/images/plug.png'),
  gallery: require('../assests/icons/gallery.png'),
  galleryWhite: require('../assests/icons/gallery-white.png'),
  music3: require('../assests/icons/music3.png'),
  music3White: require('../assests/icons/music-white.png'),
  eventIcon: require('../assests/icons/event.png'),
  eventWhite: require('../assests/icons/event-white.png'),
  pMusic: require('../assests/icons/p-music.png'),
  RatingIcon: require('../assests/icons/rating.png'),
  ImageIcon: require('../assests/icons/ImageIcon.png'),
  MusicIcon: require('../assests/icons/musicIcon.png'),
  CalendarIcon: require('../assests/icons/calendar.png'),
  UploadIcon: require('../assests/icons/uploadIcon.png'),
  MarketIcon: require('../assests/icons/market.png'),
  logoWhite: require('../assests/images/logo-white.png'),
  profile: require('../assests/icons/profile.png'),
  profileActive: require('../assests/icons/profile-active.png'),
  home: require('../assests/icons/home.png'),
  menu: require('../assests/icons/menu.png'),
  arrowLeft: require('../assests/icons/arrow-left.png'),
  sound: require('../assests/icons/sound.png'),
  spotify: require('../assests/icons/spotify.png'),
  more: require('../assests/icons/more.png'),
  music2: require('../assests/icons/music2.png'),
  headphone: require('../assests/icons/headphone.png'),
  close: require('../assests/icons/close.png'),
  play: require('../assests/icons/play.png'),
  pause: require('../assests/icons/pause.png'),
  logout: require('../assests/icons/logout.png'),
  locationGreen: require('../assests/icons/location-green.png'),
  musicIcon: require('../assests/images/musicIcon.png'),
  banner: require('../assests/images/EventBanner.png'),
  user2: require('../assests/images/user-2.png'),
  post2: require('../assests/images/post2.png'),
  navVert: require('../assests/icons/nav_vert.png'),
  pin: require('../assests/icons/pin.png'),
  shoppingCart: require('../assests/icons/shopping-cart.png'),
  chat: require('../assests/icons/chat.png'),
  audio: require('../assests/images/audio.png'),
  event: require('../assests/images/event.png'),
  product: require('../assests/images/product.png'),
  send: require('../assests/icons/send.png'),
};

export default images;
